@startuml
[Client Interface] --> [Server]
[Server] --> [Command Parser]
[Command Parser] --> [KeyValueStore]
[Command Parser] --> [SnapshotEngine]
[Other RESP-compatible clients] --> [Server]

note left of [Client Interface]
  A Python console receiving client commands
  (SET, GET, DEL, SAVE)
end note
note right of [Other RESP-compatible clients]
  Official Redis client executable: Redis-cli
end note

note right of [Server]
  Listens for commands via RESP protocol
end note

note right of [Command Parser]
Parses simplified Redis comand in RESP format
end note

note right of [KeyValueStore]
  Manages in-memory storage(database)
  for SET, GET, DEL
end note

note right of [SnapshotEngine]
  Handles saving data to disk (e.g., RDB snapshots, AOF).
  Writes current DB state to `.snap` file
  using background child process for SAVE command
end note

@enduml