@startuml
left to right direction

actor "Lập trình viên" as Developer
actor "Người kiểm thử" as Tester
actor "Người dùng" as Student

rectangle "Hệ thống lọc web đen" {

    usecase "Quản lý dữ liệu key-value\n(SET/GET/DEL/EXISTS)" as UC1
    usecase "Phân tích cú pháp RESP" as UC2
    usecase "Gửi/nhận lệnh qua TCP" as UC3

    usecase "Ghi log thao tác" as UC4
    usecase "Lưu snapshot dữ liệu ra file" as UC5


    usecase "CLI quản trị hệ thống" as UC6
    usecase "Kiểm thử bằng Redis-CLI/Python client" as UC7

}

Developer --> UC1
Developer --> UC3
Developer --> UC5
Developer --> UC6

Tester --> UC1
Tester --> UC3
Tester --> UC7

Student --> UC2
Student --> UC5



@enduml
