name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cxx: [clang++-17, g++-13, g++-14]
        preset: [vcpkg-debug, vcpkg-release]
        include:
          - cxx: clang++-17
            cxxflags: -stdlib=libc++
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build

      - name: Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $HOME/vcpkg
          sh $HOME/vcpkg/bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$HOME/vcpkg" >> $GITHUB_ENV

      - name: Configure
        env:
          CXX: ${{matrix.cxx}}
          CXXFLAGS: ${{matrix.cxxflags}}
        run: cmake --preset vcpkg

      - name: CMake Build
        run: cmake --build --preset ${{matrix.preset}} -j8

      - name: Unit test
        run: sh scripts/unit_test.sh

      - name: Test server
        run: sh scripts/test_server.sh ${{matrix.preset}}