name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [g++-13]
        preset: [vcpkg-debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build 

      - name: Add Ubuntu mirrors
        run: |
          # GitHub Actions caching proxy is at times unreliable
          # see https://github.com/actions/runner-images/issues/7048.
          mirrors=/etc/apt/mirrors.txt
          printf 'http://azure.archive.ubuntu.com/ubuntu\tpriority:1\n' | \
            sudo tee $mirrors
          curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append $mirrors
          sudo sed -i \
            "s~http://azure.archive.ubuntu.com/ubuntu/~mirror+file:$mirrors~" \
            /etc/apt/sources.list

      - name: Add repositories for newer GCC
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y g++-13
        if: ${{ matrix.cxx == 'g++-13' }}

      - name: Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $HOME/vcpkg
          sh $HOME/vcpkg/bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$HOME/vcpkg" >> $GITHUB_ENV

      - name: Configure
        env:
          CXX: ${{matrix.cxx}}
        run: cmake --preset vcpkg

      - name: CMake Build
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        run: cmake --build --preset ${{matrix.preset}} -j8

      - name: Unit test
        run: sh scripts/unit_test.sh
      - name: Test server
        run: sh scripts/test_server.sh ${{matrix.preset}}

